### ISSUE TITLE
Suggestion: Set a maximum luminosity

### ISSUE THREAD

**Issue by RomainPastureau** [MarkelZ/pygame-light2d#7]
Hi again! I am opening another topic to know if you would think to be possible to have a parameter that defines a max luminosity for a given scene. The problem I am facing now is that if two lights are too close from each other, the resulting brightness will be super white, starting to obscure parts of the scene. If it was possible to say that the maximum luminosity was, for example, 1, then we would be able to obtain a scene without any over-exposition. Adding lights on the same point would not increase the brightness of that point over the given 
threshold.

Thank you :)

**Comment by MarkelZ** [comment]
Hi again @RomainPastureau! I agree with you, the lights can get very bright and I was considering doing something about it too. What about modifying `fragment_mask.glsl`? I created a `maxLuminosity` and clamp the light value between `0` and `maxLuminoxity`:

```glsl
#version 330 core

in vec2 fragmentTexCoord;
uniform sampler2D imageTexture;

uniform sampler2D lightmap;

uniform vec4 ambient;

uniform float maxLuminosity = 2.5f; // New variable

out vec4 color;

void main()
{
    vec4 texcolor=texture(imageTexture,fragmentTexCoord);
    vec4 lightVal=texture(lightmap,fragmentTexCoord);

    lightVal=clamp(lightVal, 0, maxLuminosity); // Clamp the light value

    color=texcolor*(ambient+lightVal);
}
```

Btw you can also change this value from the Python script since it is a [uniform](https://www.khronos.org/opengl/wiki/Uniform_(GLSL)).

**Comment by RomainPastureau** [comment]
My knowledge in OpenGL is close to 0, so I would not be sure how to modify this - however if it is possible to do it from Python, I will try! Thank you!

**Comment by MarkelZ** [comment]
Hi! I just pushed these changes in [commit 038d866](https://github.com/MarkelZ/pygame-light2d/commit/038d8667832fd11bb73e644b1f781e64370babec) because it is a nice feature to have. You can simply do

```py
engine.max_luminosity = number
```

However, I haven't uploaded this to PyPI yet since I want to rewrite all the code anyway, so you can't install it with `pip`. For now, you can just clone the repo and install the package locally with `pip install .`.

**Comment by MarkelZ** [comment]
As of v1.2.0 this is a feature of the engine, so I'll mark the issue as completed. Thanks again for the feedback :)
